### ISSUE TITLE
On some recurring calls, Deserialize errors happens

### ISSUE THREAD

**Issue by mermich** [smartsheet-platform/smartsheet-csharp-sdk#133]
On some recurring calls, Deserialize errors happens. Any clue why it happen and when the issue will be solved ?

```
Unexpected character encountered while parsing value: <. Path '', line 0, position 0. Smartsheet.Api.SmartsheetException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> Smartsheet.Api.Internal.Json.JsonSerializationException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Smartsheet.Api.Internal.Json.JsonNetSerializer.deserialize[T](StreamReader inputStream)
   --- End of inner exception stack trace ---
   at Smartsheet.Api.Internal.Json.JsonNetSerializer.deserialize[T](StreamReader inputStream)
   at Smartsheet.Api.Internal.AbstractResources.HandleError(HttpResponse response)
   --- End of inner exception stack trace ---
   at Smartsheet.Api.Internal.AbstractResources.HandleError(HttpResponse response)
   at Smartsheet.Api.Internal.AbstractResources.ListResourcesWithWrapper[T](String path)
   at Smartsheet.Api.Internal.UserResourcesImpl.ListUsers(IEnumerable`1 emails, IEnumerable`1 includes, PaginationParameters paging)
   at Smartsheet.Api.Internal.UserResourcesImpl.ListUsers(IEnumerable`1 emails, PaginationParameters paging)
```

**Comment by mermich** [comment]
Currently using dotnet core 3.1, NewtonsoftJson 13.0.1 and smartsheetsdk 2.126 version.
